name: tilscore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.0.5
  - conda-forge::r-dplyr=1.0.5
  - conda-forge::r-readr=1.4.0
  - conda-forge::r-optparse=1.6.6
  - bioconda::bioconductor-singscore=1.10.0
